; Configuration file for RepRapFirmware on Duet 2 Ethernet
; executed by the firmware on start-up
;
; generated by RepRapFirmware Configuration Tool v3.6.15 on Tue Sep 08 2026 00:25:59 GMT-0600 (Mountain Daylight Time)

; General
G90 ; absolute coordinates
M83 ; relative extruder moves
M550 P"MercuryOne" ; set hostname (mDNS: mercuryone.local)

; Network
M552 P0.0.0.0 S1 ; configure Ethernet adapter
M586 P0 S1 ; configure HTTP

; Smart Drivers
M569 P0 S0 D2 ; driver 0 goes backwards (X axis)
M569 P1 S0 D2 ; driver 1 goes backwards (Y axis)
M569 P2 S0 D2 ; driver 2 goes backwards (Z axis)
M569 P3 S1 D2 ; driver 3 goes forwards (extruder 0)

; Motor Idle Current Reduction
M906 I30 T30 ; set motor current idle factor and idle timeout

; Axes
M584 X0 Y1 Z2 ; set axis mapping
M350 X16 Y16 Z16 I1 ; configure microstepping with interpolation
M906 X1600 Y1600 Z800 ; set axis driver currents  ; XY: Fabreeko Honey Badger 42HS48-25044A, 2.5 A rated (1.25 ohm, 1.8 mH, ~54 N.cm); 1600 mA = 64 % of rated, RRF guidance 60-85 %, TMC2660 max 2.4 A; 800 mA was the old stock-motor value. Z: two stock Creality 42-34 in series (0.8 A rated, 34 mm), 800 mA is 100 % of rated; fine for intermittent Z moves with I30 idle, do not raise
M92 X80 Y80 Z800 ; configure steps per mm
M208 X0:365 Y0:332 Z0:400 ; usable area, measured 2026-09-08: 0,0 = front-left clear of bed clips; endstops sit at X375 Y345 (set by G92 in homing macros); Z400 verified clear of the electronics enclosure 2026-09-11
M566 X480 Y480 Z30 P1 ; set maximum instantaneous speed changes (mm/min)  ; 8 mm/s XY (~Klipper SCV 5); Z from old E5+ config; P1 = jerk policy recommended for CoreXY
M203 X15000 Y15000 Z500 ; set maximum speeds (mm/min)  ; 250 mm/s XY, the untuned/stock-motor consensus for the Mercury One.1 (2026-09-09 survey); Z from old E5+ config
M201 X5000 Y5000 Z100 ; set accelerations (mm/s^2)  ; 2026-09-10: Klipper ringing tower at 5000 mm/s2, 100 mm/s, no shaper: no measurable ringing; Honey Badgers at 1600 mA also ran 6000 in the accelerometer test

; Extruders
M584 E3 ; set extruder mapping
M350 E16 I1 ; configure microstepping with interpolation
M906 E800 ; set extruder driver currents  ; Sherpa Mini clone motor is 1.0 A rated (Amazon B0CNPG9QB2); 600 mA skipped against the Rapido at 220 C, 800 mA does not
M92 E585 ; configure steps per mm  ; measured 2026-09-09: 720 delivered 61.5 mm per 50 commanded (clone gearing is not 50:10)
M566 E300 ; set maximum instantaneous speed changes (mm/min)
M203 E6000 ; set maximum speeds (mm/min)
M201 E1500 ; set accelerations (mm/s^2)
M572 D0 S0.12 ; pressure advance, Overture PETG 245 C, from two towers 2026-09-10: 0.12 sharpest, rounding from 0.16 (at 3000 mm/s2, 8 mm/s jerk)

; Input shaping: OFF. 2026-09-10 accelerometer measurement (Betaflight FC on the toolhead, 288 Hz): at 250 mm/s,
; 6000 mm/s2 the toolhead shows only a weak ~28-30 Hz peak (~0.004 g) and MZV 29 Hz made no measurable difference.
; Re-measure if acceleration goes above ~6000 or ringing appears in prints. See measurements/ and scripts/ringing_fft.py.
M593 P"none"

; Filament Monitors
M591 D0 P1 C"e0stop" S1 ; configure simple filament monitor for extruder 0

; Kinematics
M669 K1 ; configure CoreXY kinematics

; Probes
M558 K0 P9 C"^zprobe.in" H5 F300:120 T6000 R0.5 ; configure BLTouch probe via slot #0; fast approach 5 mm/s, final probe 2 mm/s; R0.5 recovery time before probing
G31 P500 X-25.1 Y-23.0 Z1.485 ; probe offset (sharpie-dot) and trigger height (paper test, 3 probes within 0.005 mm) measured 2026-09-09
M950 S0 C"exp.heater3" ; create servo #0 for BLtouch

; Endstops
M574 X2 P"xstop" S1 ; configure X axis endstop
M574 Y2 P"ystop" S1 ; configure Y axis endstop
M574 Z1 S2 ; configure Z axis endstop

; Bed levelling screws (manual bed levelling assistant, used by bed.g; order must match the G30 P points there)
M671 X32.9:332.9:332.9:32.9 Y35.5:37.5:297.5:295.5 P0.55 ; measured 2026-09-09 with the probe pin: front-left, front-right, rear-right, rear-left. P = effective mm per knob turn at the probe point (measured 0.55; thread is M4x0.7). Knob clockwise seen from below = corner DOWN

; Mesh Bed Compensation
M557 X30:330 Y30:300 S60:54 ; define grid for mesh bed compensation  ; 6x6; TODO: recompute once G31 X/Y offsets are measured so every probe point is on the bed

; Sensors
M308 S0 P"bedtemp" Y"thermistor" A"Heated Bed" T100000 B4092 ; configure sensor #0
M308 S1 P"e0temp" Y"thermistor" A"Nozzle" T100000 B4267 C7.06e-8 ; configure sensor #1

; Heaters
M950 H0 C"bedheat" T0 ; create heater #0
M143 H0 P0 T0 C0 S120 A0 ; configure heater monitor #0 for heater #0
M307 H0 R0.168 K0.150:0.000 D5.67 E1.35 S1.00 B0 ; bed model from M303 H0 S100, 2026-09-08 (same as config-override.g)
M950 H1 C"e0heat" T1 ; create heater #1
M143 H1 P0 T1 C0 S290 A0 ; configure heater monitor #0 for heater #1
M307 H1 R7.845 K0.743:0.444 D3.56 E1.35 S1.00 B0 V24.1 ; hotend model from M303 T0 S250, 2026-09-08, bare block (same as config-override.g)

; Heated beds
M140 P0 H0 ; configure heated bed #0

; Fans
M950 F0 C"fan0" ; create fan #0
M106 P0 C"Hotend Fan" S0 X1 B0.1 H1 T45 ; configure fan #0 (heatsink fan, thermostatic on nozzle sensor)
M950 F1 C"fan2" ; create fan #1
M106 P1 C"Cooling Fan" S0 X1 B0.1 H-1 ; configure fan #1 (part cooling, slicer controlled)

; Tools
M563 P0 S"Rapido2" D0 H1 F1 ; create tool #0 (F1 = part cooling fan)
M568 P0 R0 S0 ; set initial tool #0 active and standby temperatures to 0C

; Power loss recovery (needs resurrect-prologue.g to home XY on resume; resume with M916)
M911 S19.8 R22 P"M913 X0 Y0 G91 M83 G1 Z3 E-5 F1000" ; on VIN < 19.8V: drop XY current, lift Z 3mm, retract 5mm; re-arm above 22V

; Miscellaneous
M501 ; load saved parameters from non-volatile memory
T0 ; select first tool
