; deployprobe0.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.6.15 on Tue Sep 08 2026 00:26:05 GMT-0600 (Mountain Daylight Time)

M280 P0 S10	; deploy BLTouch
G4 P500	; wait for the pin to fully extend before probing (2026-09-08: probing without this crashed the bed)
