; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool v3.6.15 on Tue Sep 08 2026 00:26:06 GMT-0600 (Mountain Daylight Time)

; increase Z
G91 ; relative positioning
G1 H2 Z5 ; move Z relative to current position to avoid dragging nozzle over the bed
G90 ; absolute positioning

; home Y
G91 ; relative positioning
var maxTravel = move.axes[1].max - move.axes[1].min + 20 ; Y travel plus margin (endstop is 13mm beyond Y max)
G1 H1 Y{var.maxTravel} F3000 ; coarse home in the +Y direction
G1 Y-5 F6000 ; move back 5mm
G1 H1 Y{var.maxTravel} F300 ; fine home in the +Y direction
M564 S0 ; allow position outside limits for G92
G92 Y345 ; endstop is 13mm beyond Y max; set true position
M564 S1 ; re-enable software limits
G90 ; absolute positioning

; decrease Z again
G91 ; relative positioning
G1 H2 Z-5 F6000 ; move Z relative to current position
G90 ; absolute positioning
