; homeall.g
; called to home all axes
;
; generated by RepRapFirmware Configuration Tool v3.6.15 on Tue Sep 08 2026 00:26:05 GMT-0600 (Mountain Daylight Time)

; increase Z
G91 ; relative positioning
G1 H2 Z5 F6000 ; move Z relative to current position to avoid dragging nozzle over the bed
G90 ; absolute positioning

; home XY
var xTravel = move.axes[0].max - move.axes[0].min + 20 ; X travel plus margin (endstop is 10mm beyond X max)
var yTravel = move.axes[1].max - move.axes[1].min + 20 ; Y travel plus margin (endstop is 13mm beyond Y max)
G91 ; relative positioning
G1 H1 X{var.xTravel} Y{var.yTravel} F3000 ; coarse home
G1 H1 X{var.xTravel} F3000 ; coarse home in the +X direction
G1 H1 Y{var.yTravel} F3000 ; coarse home in the +Y direction
G1 X-5 Y-5 F6000 ; move back 5mm
G1 H1 X{var.xTravel} Y{var.yTravel} F300 ; fine home
G1 H1 X{var.xTravel} F300 ; fine home in the +X direction
G1 H1 Y{var.yTravel} F300 ; fine home in the +Y direction
M564 S0 ; allow position outside limits for G92 (RRF clamps G92 otherwise)
G92 X375 Y345 ; endstops are beyond the usable area (M208 max); set true position
M564 S1 ; re-enable software limits
G90 ; absolute positioning

; home Z
var xCenter = move.compensation.probeGrid.mins[0] + (move.compensation.probeGrid.maxs[0] - move.compensation.probeGrid.mins[0]) / 2 - sensors.probes[0].offsets[0]
var yCenter = move.compensation.probeGrid.mins[1] + (move.compensation.probeGrid.maxs[1] - move.compensation.probeGrid.mins[1]) / 2 - sensors.probes[0].offsets[1]
G1 X{var.xCenter} Y{var.yCenter} F6000 ; go to bed centre
G30 ; probe the bed


