; homex.g
; called to home the X axis
;
; generated by RepRapFirmware Configuration Tool v3.6.15 on Tue Sep 08 2026 00:26:06 GMT-0600 (Mountain Daylight Time)

; increase Z
G91 ; relative positioning
G1 H2 Z5 ; move Z relative to current position to avoid dragging nozzle over the bed
G90 ; absolute positioning

; home X
G91 ; relative positioning
var maxTravel = move.axes[0].max - move.axes[0].min + 20 ; X travel plus margin (endstop is 10mm beyond X max)
G1 H1 X{var.maxTravel} F3000 ; coarse home in the +X direction
G1 X-5 F6000 ; move back 5mm
G1 H1 X{var.maxTravel} F300 ; fine home in the +X direction
M564 S0 ; allow position outside limits for G92
G92 X375 ; endstop is 10mm beyond X max; set true position
M564 S1 ; re-enable software limits
G90 ; absolute positioning

; decrease Z again
G91 ; relative positioning
G1 H2 Z-5 F6000 ; move Z relative to current position
G90 ; absolute positioning
