; resume.g
; called before a print from SD card is resumed
;
; generated by RepRapFirmware Configuration Tool v3.6.15 on Tue Sep 08 2026 00:26:06 GMT-0600 (Mountain Daylight Time)
G1 R1 X0 Y0 Z5 F6000 ; go to 5mm above position of the last move
G1 R1 X0 Y0 Z0 ; go back to the last print move
M83 ; relative extruder moves
G1 E10 F3600 ; extrude 10mm of filament
