; retractprobe0.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.6.15 on Tue Sep 08 2026 00:26:06 GMT-0600 (Mountain Daylight Time)

M280 P0 S90	; retract BLTouch
G4 P200	; let the pin settle
