; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.6.15 on Tue Sep 08 2026 00:26:07 GMT-0600 (Mountain Daylight Time)

M116 P0 ; wait for tool temperatures to be reached
