#!/usr/bin/env python3
"""Generate a ringing test print for input shaping on MercuryOne (no slicer needed).

Single-perimeter square (thin walls ring visibly), sharp corners, constant known
speed, acceleration raised for the test. Afterwards measure the ripple spacing on
a wall right after a corner with a ruler under raking light:
    ringing frequency (Hz) = print speed (mm/s) / ripple spacing (mm)
Walls printed along X (the front/back walls) show the X ringing; the side walls show Y.
Then: M593 P"mzv" F<freq> (or separate X/Y: M593 P"mzv" F<fx>:<fy> is not supported on
RRF, use one frequency or the DWC Input Shaping plugin with an accelerometer).

    scripts/gen_ringing_test.py out.gcode [--size 60] [--height 25] [--speed 120] [--accel 5000]
                                [--temp 245] [--bed 80] [--pa 0.11]
"""
import argparse, math
ap = argparse.ArgumentParser()
ap.add_argument('dst')
ap.add_argument('--size', type=float, default=60); ap.add_argument('--height', type=float, default=25)
ap.add_argument('--speed', type=float, default=120); ap.add_argument('--accel', type=float, default=5000)
ap.add_argument('--temp', type=float, default=245); ap.add_argument('--bed', type=float, default=80)
ap.add_argument('--pa', type=float, default=0.11)
ap.add_argument('--layer', type=float, default=0.2); ap.add_argument('--width', type=float, default=0.45)
ap.add_argument('--cx', type=float, default=182); ap.add_argument('--cy', type=float, default=166)
a = ap.parse_args()
fil_area = math.pi * (1.75 / 2) ** 2
epm = a.width * a.layer / fil_area
def square(half, feed):
    x0, y0 = a.cx - half, a.cy - half; x1, y1 = a.cx + half, a.cy + half
    pts = [(x0, y0), (x1, y0), (x1, y1), (x0, y1), (x0, y0)]
    out = [f'G1 X{pts[0][0]:.3f} Y{pts[0][1]:.3f} F6000']
    for (px, py), (qx, qy) in zip(pts, pts[1:]):
        out.append(f'G1 X{qx:.3f} Y{qy:.3f} E{math.hypot(qx-px, qy-py)*epm:.4f} F{feed:.0f}')
    return out
g = [f'; ringing test generated by gen_ringing_test.py: {a.size}mm square, {a.height}mm, {a.speed} mm/s, accel {a.accel}, PA {a.pa}, {a.temp}C/{a.bed}C',
     f'M140 S{a.bed:g}', 'M104 S150', 'G28', 'G29 S1', f'M190 S{a.bed:g}', 'G1 X5 Y3 Z10 F6000', f'M109 S{a.temp:g}',
     'M83', 'G92 E0', 'G1 Z0.3 F300', 'G1 X120 Y3 E12 F900', 'G1 X120 Y3.6 F3000', 'G1 X30 Y3.6 E4 F900', 'G92 E0', 'G1 Z2 F300',
     f'M572 D0 S{a.pa:g}', 'M593 P"none" ; make sure no input shaper is active for the test', 'M106 S0']
n = int(round(a.height / a.layer))
for i in range(n):
    z = a.layer * (i + 1)
    g += [';LAYER_CHANGE', f';Z:{z:.2f}', f'G1 Z{z:.2f} F300']
    if i == 0:
        g.append('M204 P1500 ; gentle first layer')
        for k in range(6, 0, -1): g += square(a.size / 2 + k * a.width, 30 * 60)
        g += square(a.size / 2, 30 * 60); g += square(a.size / 2 - a.width, 30 * 60)
        continue
    if i == 1: g += ['M106 S128', f'M204 P{a.accel:g} T{a.accel:g} ; high accel so the ringing shows']
    if i < 5: g += square(a.size / 2 - a.width, 60 * 60)   # 2 perimeters for the first mm of the tower
    g += square(a.size / 2, a.speed * 60)
g += ['M204 P2000 T2000 ; restore', 'M104 S0', 'M140 S0', 'M83', 'G1 E-3 F1800', 'G91', 'G1 Z10 F300', 'G90', 'G1 X5 Y325 F6000', 'M106 S0', 'M84']
open(a.dst, 'w').write('\n'.join(g) + '\n')
print(f'{n} layers, walls at {a.speed} mm/s, accel {a.accel}; est ~{n*(4*a.size/a.speed+1.5)/60:.0f} min')
