#!/usr/bin/env python3
"""Generate a pressure-advance test tower for MercuryOne without a slicer.

Square tower, 2 perimeters + brim, sharp corners, outer wall fast. PA (M572 D0)
steps up every --band mm. Read the print: the band whose corners are neither
bulged (PA too low) nor gapped/rounded (PA too high) is the value to keep.

    scripts/gen_pa_tower.py out.gcode [--size 40] [--height 60] [--band 5] [--start 0] [--step 0.01]
                            [--temp 245] [--bed 80] [--speed 100] [--inner 60]
"""
import argparse, math
ap = argparse.ArgumentParser()
ap.add_argument('dst')
ap.add_argument('--size', type=float, default=40); ap.add_argument('--height', type=float, default=60)
ap.add_argument('--band', type=float, default=5); ap.add_argument('--start', type=float, default=0.0)
ap.add_argument('--step', type=float, default=0.01)
ap.add_argument('--temp', type=float, default=245); ap.add_argument('--bed', type=float, default=80)
ap.add_argument('--speed', type=float, default=100); ap.add_argument('--inner', type=float, default=60)
ap.add_argument('--layer', type=float, default=0.2); ap.add_argument('--width', type=float, default=0.45)
ap.add_argument('--cx', type=float, default=182); ap.add_argument('--cy', type=float, default=166)
a = ap.parse_args()

fil_area = math.pi * (1.75 / 2) ** 2
def e_per_mm(w, h): return w * h / fil_area
g = []
g += [
 f'; PA tower generated by gen_pa_tower.py: {a.size}mm square, {a.height}mm tall, PA {a.start} + {a.step}/band, band {a.band}mm, {a.temp}C/{a.bed}C',
 f'M140 S{a.bed:g}', 'M104 S150', 'G28', 'G29 S1', f'M190 S{a.bed:g}', 'G1 X5 Y3 Z10 F6000', f'M109 S{a.temp:g}',
 'M83', 'G92 E0', 'G1 Z0.3 F300', 'G1 X120 Y3 E12 F900', 'G1 X120 Y3.6 F3000', 'G1 X30 Y3.6 E4 F900', 'G92 E0', 'G1 Z2 F300',
 'M572 D0 S0 ; PA off for the brim/first layer', 'M106 S0',
]
def square(half, z, feed, epm):
    x0, y0 = a.cx - half, a.cy - half; x1, y1 = a.cx + half, a.cy + half
    pts = [(x0, y0), (x1, y0), (x1, y1), (x0, y1), (x0, y0)]
    out = [f'G1 X{pts[0][0]:.3f} Y{pts[0][1]:.3f} F6000']
    for (px, py), (qx, qy) in zip(pts, pts[1:]):
        out.append(f'G1 X{qx:.3f} Y{qy:.3f} E{math.hypot(qx-px, qy-py)*epm:.4f} F{feed:.0f}')
    return out
n_layers = int(round(a.height / a.layer)); band_seen = -1
for i in range(n_layers):
    z = a.layer * (i + 1); first = (i == 0)
    g += [';LAYER_CHANGE', f';Z:{z:.2f}', f'G1 Z{z:.2f} F300']
    if first:
        # brim: 6 loops outside the outer wall, then the two perimeters, all slow
        for k in range(6, 0, -1):
            g += square(a.size / 2 + k * a.width, z, 30 * 60, e_per_mm(a.width, a.layer))
        g += square(a.size / 2, z, 30 * 60, e_per_mm(a.width, a.layer))
        g += square(a.size / 2 - a.width, z, 30 * 60, e_per_mm(a.width, a.layer))
        continue
    if i == 2: g.append('M106 S128 ; part fan 50% from layer 3')
    band = int((z - 1e-6) // a.band)
    if band != band_seen:
        band_seen = band
        g.append(f'M572 D0 S{a.start + a.step * band:.3f} ; band {band} from Z {z:.1f}')
    g += square(a.size / 2 - a.width, z, a.inner * 60, e_per_mm(a.width, a.layer))   # inner perimeter first
    g += square(a.size / 2, z, a.speed * 60, e_per_mm(a.width, a.layer))            # outer perimeter fast
g += ['M572 D0 S0', 'M104 S0', f'M140 S0', 'M83', 'G1 E-3 F1800', 'G91', 'G1 Z10 F300', 'G90', 'G1 X5 Y325 F6000', 'M106 S0', 'M84']
open(a.dst, 'w').write('\n'.join(g) + '\n')
bands = [(b, a.start + a.step * b) for b in range(int(a.height // a.band))]
print(f'{n_layers} layers, {len(bands)} bands: ' + ', '.join(f'{b*a.band:g}-{(b+1)*a.band:g}mm PA {pa:.2f}' for b, pa in bands))
